### ISSUE TITLE
"read: connection refused" After Update to 0.3.0 and Later

### ISSUE THREAD

**Issue by JaydenMcEncroe** [natesales/q#1]
Hello,

After update to 0.3.0 and later, attempt to q a domain will result to fellowing error.
```
$ q  google.com
FATA[0000] upstream query: read udp 127.0.0.1:48651->127.0.0.1:53: read: connection refused
```
It can be bypassed by manuely specify an external DNS server, e.g. 
```
$ q -s 8.8.8.8 google.com
google.com. 1m36s A 216.58.196.142
google.com. 4m59s AAAA 2404:6800:4006:805::200e
google.com. 1h18m4s NS ns2.google.com.
google.com. 1h18m4s NS ns1.google.com.
google.com. 1h18m4s NS ns3.google.com.
google.com. 1h18m4s NS ns4.google.com.
google.com. 59m59s TXT "google-site-verification=TV9-DBe4R80X4v0M4U_bd_J9cpOJM0nikft0jAgjmsQ"
google.com. 59m59s TXT "MS=E4A68B9AB2BB9670BCE15412F62916164C0B20BB"
google.com. 59m59s TXT "globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8="
```

Best wishes

**Comment by natesales** [comment]
This is a result of removing the previous hardcoded default DNS server. Due to the way the standard library handles DNS queries, it's not trivial to use the default system resolver for all query types. `v0.3.2` brings back Cloudflare DoH as the default resolver, so you'll be able to make queries without supplying a server.

**Comment by JaydenMcEncroe** [comment]
I saw the update today and it works, thanks!
